export const instructorNotes = [
  {
    id: 'CC-241202',
    title: 'The Monday Scorecard',
    readiness: 'validated',
    truth: 'Both opening scorecards can be arithmetically correct. The divergence combines incompatible 1–5 and 1–10 survey scales, migration-era duplicate source tickets, and non-random survey response. There is no secret preferred aggregation.',
    watchFor: 'Raw-score averaging, deleting every repeated-looking ticket, or generalizing respondent satisfaction to every customer.',
  },
  {
    id: 'IO-250320',
    title: 'Rollback Before Dawn',
    readiness: 'validated',
    truth: 'A severe winter event, missing-not-at-random telemetry, a firmware measurement shift, and a scoped Great Lakes issue overlap. The release does not identify a clean firmware-only physical effect or justify a single hidden rollback answer.',
    watchFor: 'Treating missing telemetry as healthy equipment, using delayed outcomes at the decision time, or mistaking a measurement shift for physical failure.',
  },
  {
    id: 'FD-250930',
    title: 'The Orion Renewal',
    readiness: 'validated',
    truth: 'ORION-2 creates a real operating-regime change but no clean 12% causal productivity answer. Adoption has no untreated geographic control, route stops are not work-order grain, and joins across histories and parts multiply rows.',
    watchFor: 'Claiming causal ROI from before/after averages, counting rescheduled work twice, or ranking technicians without addressing assignment policy.',
  },
  {
    id: 'ML-260115',
    title: 'Too Good to Ship',
    readiness: 'validated',
    truth: 'The near-perfect model is invalid: future outcomes leak into predictors, accounts cross random row splits, time is mixed, and governance/deployment evidence is absent. A post-audit AUC is not a grading target.',
    watchFor: 'Prefix-only leakage removal, random row splitting, or treating offline discrimination as deployment approval.',
  },
  {
    id: 'FI-240708',
    title: 'The Quarter That Moved',
    readiness: 'validated',
    truth: 'Acquired-system order numbers are tenant-local and some timestamps are shifted by about five hours. Canonical order IDs, captured transaction amounts, named clocks, and a frozen cutoff can reconcile the quarter; price history is not a sales ledger.',
    watchFor: 'Deduplicating on an unnamespaced source ID, overwriting captured price, or joining several one-to-many tables before aggregation.',
  },
  {
    id: 'PX-250505',
    title: 'The Navigation Vote',
    readiness: 'validated',
    truth: 'Treatment genuinely increases session event depth, but the estate does not label whether the extra depth is useful or frustrating and does not encode a matching conversion effect. Session is the registered assignment unit.',
    watchFor: 'Weighting deep sessions more heavily through event joins, redefining eligibility from the experiment name, or interpreting no significant conversion difference as equivalence.',
  },
  {
    id: 'OP-250320',
    title: 'The 7:30 Capacity Call',
    readiness: 'validated',
    truth: 'Convenient final-state tables leak the future. The point-in-time target is appointment-window breach; storm exposure and window length contain real signal, while the decision population shifts during the storm. Risk is not treatment effect.',
    watchFor: 'Using realized arrival/completion facts, optimizing AUC without a capacity policy, or turning technician identity into an employee score.',
  },
  {
    id: 'AI-251006',
    title: 'The Queue Nobody Owns',
    readiness: 'validated with a deliberate refusal path',
    truth: 'The current text templates, subjects, categories, and teams are generated independently, while the available team label is final rather than adjudicated initial ownership. Honest clean-holdout routing signal may be insufficient; refusing launch and designing shadow labels is a successful outcome.',
    watchFor: 'Using later agent messages, accepting final assignment as ground truth, overlooking duplicate interactions, or forcing a classifier to win.',
  },
  {
    id: 'SC-251118',
    title: 'Forty-Eight Hours of Stock',
    readiness: 'data repair in progress',
    truth: 'Do not assign this case yet. Its forecasting mechanism and inventory reconciliation checks remain intentionally unpublished until the supply generator passes exact invariants.',
    watchFor: 'Teaching from a plausible narrative before replay links, receipts, lead times, and physical inventory actually reconcile in the generated estate.',
  },
] as const;
