#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

from config import CATALOG_ROOT


def quote(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def write_duckdb_views(catalog: list[dict]) -> Path:
    """Write a portable SQL facade over the Parquet estate."""
    schemas = sorted({item["schema"] for item in catalog})
    lines = [
        "-- Generated by generator/write_duckdb_views.py.",
        "-- Run from the repository root: duckdb < catalog/create_duckdb_views.sql",
        "",
    ]
    for schema in schemas:
        lines.append(f"CREATE SCHEMA IF NOT EXISTS {quote(schema)};")
    lines.append("")
    for item in sorted(catalog, key=lambda row: row["fully_qualified_name"]):
        schema = quote(item["schema"])
        table = quote(item["table"])
        relative_path = item["relative_path"].replace("'", "''")
        lines.append(
            f"CREATE OR REPLACE VIEW {schema}.{table} AS "
            f"SELECT * FROM read_parquet('{relative_path}');"
        )
    lines.append("")
    output = CATALOG_ROOT / "create_duckdb_views.sql"
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def main() -> int:
    catalog = json.loads((CATALOG_ROOT / "data_catalog.json").read_text())
    output = write_duckdb_views(catalog)
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
